# Generated by Django 4.2 on 2023-04-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_sighting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('F', 'Fruits'), ('S', 'Seeds'), ('V', 'Vegetable')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='finch',
            name='foods',
            field=models.ManyToManyField(to='main_app.food'),
        ),
    ]
